session_name: vcspull
before_script: ./bootstrap_env.py  # ./ to load relative to project root
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: vcspull
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  shell_command_before:
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  panes:
  - focus: true
  - pane
  - if command -v entr > /dev/null; then ls vcspull/*.py *.py | entr ./run-tests.py; else ./run-tests.py; echo "\nInstall entr(1) to automatically run tests on file change.\n See http://entrproject.org/"; fi
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: doc/
  shell_command_before: 
    - '[ -d ../.venv -a -f ../.venv/bin/activate ] && source ../.venv/bin/activate'
  panes:
  - focus: true
  - pane
  - echo 'docs built to <http://0.0.0.0:8002/_build/html>'; python -m SimpleHTTPServer 8002
  - if command -v entr > /dev/null; then ls *.rst *.py ../CHANGES ../README.rst ../TODO | entr make html; else make html; echo "\nInstall entr(1) to automatically rebuild documentation when files change. \nSee http://entrproject.org/"; fi
