language: python

python:
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mercurial git-core subversion cvs
install:
  - "pip install -e ."
script: python run_tests.py
