language: python
sudo: false
dist: bionic  # 18.04
python:
  - 2.7
  - 3.7
  - pypy3
if: (type = push AND branch IN (master)) OR (type = pull_request)
cache: pip
addons:
  apt:
    packages:
    - mercurial
    - git-core
    - subversion
    - cvs
before_install:
  - git config --global user.name 'travis-ci'
  - git config --global user.email 'travis@nowhere.edu'
install:
  - pip install -e .
  - pip install -r requirements/test.txt
script: py.test --cov=vcspull
after_success:
  - bash <(curl -s https://codecov.io/bash)
