language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_install:
  - sudo apt-get update -qq
  - export PIP_USE_MIRRORS=true
  - pip install coveralls
  - sudo apt-get install -qq mercurial git-core subversion cvs
  - git config --global user.name 'travis-ci'
  - git config --global user.email 'travis@nowhere.edu'
install:
  - "pip install -e ."
# script: python setup.py test
script: coverage run --source=tmuxp setup.py test
after_success:
  - coveralls
