language: python
python:
  - 2.6
  - 2.7
  - 3.3
matrix:
  allow_failures:
    - python: 2.6
    - python: 3.3
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mercurial git-core subversion cvs
 - git config --global user.name 'travis-ci'
 - git config --global user.email 'travis@nowhere.edu'
install:
  - "pip install -e ."
script: python run_tests.py
